### ISSUE TITLE
Unable to load plugin on Linux LMS v8.2.0

### ISSUE THREAD

**Issue by ArtSpaziano** [sspiff/lms-plugin-pyrrha#12]
Error found in the log is:
Slim::Utils::PluginManager::load (237) Couldn't load Pyrrha. Error: Plugin is incompatible with this version of Logitech Media Server. Please update.

I had initially tried installing via the LMS UI and restarting the server. No plugin was installed, so I tried the manual method of placing the contents of the zip file in the plugin folder and restarting LMS.
That's when I saw the error shown above.

**Comment by ArtSpaziano** [comment]
I should also note that v8.2.0 is the latest when maintaining packages with apt package manager. I'll see if I can install this on a separate box but this may present an issues for those with Raspberry Pi depending on the package manager which appears to be a few releases behind the latest.

**Comment by sspiff** [comment]
I don't know of a reason why the plugin wouldn't work on LMS 8.2.0.  I had just set the minimum to 8.3.0 as that's what I tested with, but I can bump it down.

**Comment by ArtSpaziano** [comment]
If you think the plugin should work with 8.2.0, I'd be happy to test it after you change the minimum.

**Comment by ArtSpaziano** [comment]
Not being familiar with LMS Plugins, I didn't realize that I could change the minVersion property until this morning. I changed it to 8,2,0 and the plugin loaded and I can see the settings page.
I guess I'll need to get a paid Pandora subscription to try it out but it looks hopeful so far.

**Comment by ArtSpaziano** [comment]
No luck with my V8.2.0 install. Pyrrha doesn't appear under the Apps category. Nothing in the logs to provide any clues.
Then, I stood up a temporary PicorPlayer instance on a spare Pi4 which gives me and LMS V8.3.0 instance. Everything works as expected.

So, it looks like it V8.3.0 really is the minimum.  I'll see if I can manually upgrade my regular server outside of 'apt'.
If I still have issues, I'll just switch over to the test server I stood up for this test. 

Feel free to close this unless you would like an update on how it works on the original server after the upgrade to 8.3.0.

Art

**Comment by sspiff** [comment]
I think it should at least show up under Apps.  There are two places where the minimum version is set.  Where did you change it at?

**Comment by sspiff** [comment]
Anything interesting in the log?

**Comment by ArtSpaziano** [comment]
I changed it only in the install.xml file   - Where is the other place?

Regarding log entries, nothing related to Pyrrha - just an occasional message about Mysqueezebox authentication failures

**Comment by sspiff** [comment]
Actually, thinking about it now, the other place is in the repo.xml file, which you wouldn't be able to change.  And, if you can see the settings page for Pyrrha, then it is getting loaded.  I was going to change the minimum to 8.2 in the code base today because I really thought it would work.  Want to wait until I can push that out so you can try it?  It will probably be later this afternoon as I'm trying to roll in some other changes at the same time.

**Comment by ArtSpaziano** [comment]
I'll wait. I need to backup the server before trying the upgrade and I have a few other things to take care of.
It would be good to know that it works with v8.2.0 anyway, since that's what the the package manager likes.

**Comment by sspiff** [comment]
@ArtSpaziano Give v0.2.6 a whirl.  It "claims" support for LMS back to 8.2.0.

**Comment by ArtSpaziano** [comment]
Tried v0.2.6. Still no-show for Pyrrha under Apps.  The log did have this:
[24-02-16 17:48:14.8779] Slim::Web::Cometd::handler (421) errorNeedsClient: 00:04:20:2d:8c:3c, status, -, 10, menu:menu, useContextMenu:1, subscribe:600

I installed LMS v8.4.0 (v8.3.0 was not available for some reason) and all works as expected.

So, it looks like you may want to stick with a minimum of v8.3.0, given my experience, although it's only a sample size of 1.

In any event, many thanks. I never realized how much we depended upon the LMS / Pandora integration until this week.

You should start a fund for contributions!

**Comment by sspiff** [comment]
Sorry, not sure what the hiccup is.  Yes, will stick with a minimum of 8.3.0 for now.

**Comment by ArtSpaziano** [comment]
No worries. Gave me a chance to address falling behind in LMS versions.
