### ISSUE TITLE
Syncing to Pandora - force update?

### ISSUE THREAD

**Issue by keithpleas** [sspiff/lms-plugin-pyrrha#28]
There are already a couple of issues about adding / searching stations. Note that everything can be accomplished in the Pandora (web, app) UI - but it takes a while to sync to Pyrrha - ideally there would be a way in Pyrrha to force a sync (or perhaps shorten the polling interval). 

Linking #13 , #17

**Comment by sspiff** [comment]
The ```user.getStationListChecksum``` API may be useful in keeping the station list up-to-date.

**Comment by sspiff** [comment]
> The `user.getStationListChecksum` API may be useful in keeping the station list up-to-date.

Oh but Pyrrha isn't using that API suite for the station list any more.  Maybe the REST API will honor an ```If-Modified-Since``` HTTP header?
