### ISSUE TITLE
support free accounts

### ISSUE THREAD

**Issue by sspiff** [sspiff/lms-plugin-pyrrha#6]
Add support for free accounts.  Need #5 first.

**Comment by zekyl314** [comment]
I would agree, if this is possible, I'd really appreciate it too.  Thanks for all your hard work, it hasn't gone unnoticed.

**Comment by sspiff** [comment]
Resolved in v0.4.0 via https://github.com/sspiff/lms-plugin-pyrrha/commit/f5bcde1ca3effb07f6a20c8820f78805f136fcb4.
